### ISSUE TITLE
Crash on setParameters Camera1

### ISSUE THREAD

**Issue by sonjameyer** [wonderkiln/CameraKit-Android#132]
We are getting quite a few crashes in a live app related to camera parameters. Another one from Crashlytics:

Fatal Exception: java.lang.RuntimeException
setParameters failed 
 android.hardware.Camera.native_setParameters (Camera.java)
 android.hardware.Camera.setParameters (Camera.java:1763)
 com.flurgle.camerakit.Camera1$5.run (Camera1.java:586)

Mostly occurs on Android 4 and 5.

We are on the latest version.

**Comment by vamzi** [comment]
It might be because of native permission glitch in the app that was mentioned in readme.md, Just dont use cameraView.start() which will crash the application after the first lauch.

**Comment by hb-smeyer** [comment]
This is my code to check the permission:
@Override
    public void onStart() {
        super.onStart();
        if (ContextCompat.checkSelfPermission(this,
                Manifest.permission.CAMERA)
                != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this,
                    new String[]{Manifest.permission.CAMERA},
                    CAMERA_PERMISSION_REQUEST_CODE);
        }
        else {
            permissionGranted = true;
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (permissionGranted) {
            mCamera.start();
            enableCamera();
            mNoPermissionText.setVisibility(View.GONE);
        }
        else {
            disableCamera();
            mNoPermissionText.setVisibility(View.VISIBLE);
        }
    }

**Comment by dwillmc** [comment]
This should be fixed now with the latest release. Can you update your `build.gradle` to reference `com.wonderkiln:camerakit:0.11.1`. If the issue persists can you please re-open.

Thanks!
