### ISSUE TITLE
This library continues to be maintained?

### ISSUE THREAD

**Issue by bruferrari** [wonderkiln/CameraKit-Android#145]
Hi, guys, I've made some tests with this lib last week and some other libraries too, but this one is the one that solve my entire problems without manage some changes in another forks.

By saying that I would like to know if this lib continues to be maintained, I've seen many issues and PR's opened for a while and that was a doubt point in order to use this lib in production.

Thanks in advance.

**Comment by eduardo4jesus** [comment]
I have that same concern. I was using [larryng's fork](https://github.com/larryng/CameraKit-Android) for in the first stage of my project. He manage to solve one of the problems, but as you said, there are other Issues to be solved/merged.

As I need to move forward and get things done in my project, I am kind of forced to reinvent the wheel as well. I just decided to have my own fork and as I am facing the issues I will either look up for solutions here or, if I don't find any, solve it myself.

**Comment by austinkettner** [comment]
@bruferrari @eduardo4jesus This is still in-development and something we care about. While the progress may be slower than desired, we are 100% focused on not introducing new issues. With that said, we do have long term plans to support this just might not be blazing fast.

@dwillmc Will be spending some time on this, this week, so you will see issues closed, PRs responded to and a new release.

**Comment by bruferrari** [comment]
@eduardo4jesus it's something that I'm worried about, I've been using another lib to do the dirty job, but I'm also kinda reinventing the wheel and it's very bad for a production app because I can't count on people that have so much more knowledge than I. So, somehow it's a breaker for me to choose the best option in terms of maintenance.

_But we also know that Google Cameras APIs are very painful to handle and this library is awesome, please guys keep doing this **awesome** job! I'll help with PR's when something appear in my development path._

@austinkettner thanks for fast answer! It's good to know that you guys are focusing on keep this lib better, even if it means that we're haven't new features in near future.

**Comment by dwillmc** [comment]
You guys can feel free to email me (email on my profile) anything specific you need for your production apps and the best solutions you've found and I'll be sure to get it in a release this week

**Comment by bruferrari** [comment]
@dwillmc thanks for this awesome support guys!

**Comment by eduardo4jesus** [comment]
@dwillmc, Thank you so much for taking a look at it!

**Comment by matthewcarlreetz** [comment]
@dwillmc Any chance we could get pinch to zoom in the next release?

**Comment by dwillmc** [comment]
@matthewcarlreetz Yes that's a core focus. I'll take a look at what everybody else has tried and get something in.

**Comment by Hrishi1999** [comment]
BTW, why doesn't capturing work after .14?

**Comment by mkonkel** [comment]
Hi! 
Any news about the new release?

**Comment by austinkettner** [comment]
Hey everyone, we are closing this ticket as you can see the recent releases and support via our latest releases! If anyone runs into issue or questions, definitely feel free to open a new ticket though =)
