### ISSUE TITLE
Custom File Output Path

### ISSUE THREAD

**Issue by vishalpatel1327** [wonderkiln/CameraKit-Android#154]
Hello boss,
 This is great library  thanx for that

But I have one question   How to change default path for Camera and video save

**Comment by Ninjaman494** [comment]
The library has no built in way to do this. What I did was manually move the file in onVideoTaken using file.renameTo(newFile), where newFile is a File object containing the new file path.

**Comment by vishalpatelbacancy** [comment]
@dwillmc   for Custom path It will be great for us to add some line in code

At Camera1


//add at 267
 @Override
    void setVideoCapturePath(File path) {
        this.userGivenFile = path;
    }




// line no 779  
 private File getVideoFile() {
       
        if (!Environment.getExternalStorageState().equalsIgnoreCase(Environment.MEDIA_MOUNTED)) {
            return null;
        }
File mediaStorageDir ;
if(userGivenFile == null){
         mediaStorageDir = new File(Environment.getExternalStorageDirectory(), "Camera");
}else{
mediaStorageDir = userGivenFile;

}
        if (!mediaStorageDir.exists()) {
            if (!mediaStorageDir.mkdirs()) {
                return null;
            }
        }

        return new File(mediaStorageDir.getPath() + File.separator + "video.mp4");
    }
