### ISSUE TITLE
Mirror Image

### ISSUE THREAD

**Issue by abhinav011085** [wonderkiln/CameraKit-Android#181]
When using the front camera, I am getting mirrored image.

**Comment by developweb10** [comment]
Bitmap rotated = RotateBitmap(compressedImageBitmap);

   public static Bitmap RotateBitmap(Bitmap source) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Matrix matrix = new Matrix();
        matrix.preScale(-1.0f, 1.0f);
        return Bitmap.createBitmap(source, 0, 0, source.getWidth(), source.getHeight(), matrix, false);
    }

@abhinav011085 Please use this code to fix this issue

**Comment by abhinav011085** [comment]
Thanks, it worked.
