### ISSUE TITLE
Failed to resolve: com.wonderkiln:camerakit:0.10.1

### ISSUE THREAD

**Issue by bruferrari** [wonderkiln/CameraKit-Android#182]
Hi guys, I've notice that there was an update, but I can't update it in my gradle file, seems that the  `com.wonderkiln:camerakit:0.10.1` doesn't exists.

**Comment by Xenero** [comment]
Facing same issue here.

Have Invalidated/Restarted and also cleared gradle cache

**Comment by BuddahLD** [comment]
Hello!
The same issue as above - failed to resolve: com.wonderkiln:camerakit:0.10.1
Invalidate/Restart didn't help.

**Comment by austinkettner** [comment]
It's going to take a bit longer for Maven to update to the new package name. Should be up and available shortly! Will update this ticket once live.

**Comment by bruferrari** [comment]
I'm using it with jitpack and I can confirm that works until maven processing finish

**Comment by BuddahLD** [comment]
Hello!
I'm sorry, is the issue still present, or is it my-side problem?
Thank you!

**Comment by BuddahLD** [comment]
Hello!
The issue is still reproducible. Sorry, is this my-side problem?
Thank you!

**Comment by Xenero** [comment]
Still happening here also

**Comment by austinkettner** [comment]
Hey guys. We expect this release to be ‘live’ on Monday.

Austin L Kettner                                                                          
330.714.3513 [tel:330-714-3513] - @austinkettner [https://twitter.com/austinkettner]      
www.austinkettner.com [http://www.austinkettner.com]                                      


On Sun, Oct 1, 2017 at 12:16 PM, Brandon Stillitano <notifications@github.com> wrote:
Still happening here also

**Comment by hazelement** [comment]
Are you guys still experiencing the same issue?

**Comment by kevinstier** [comment]
Yes, I do

**Comment by austinkettner** [comment]
Still waiting on Bintray here. Apologies, but it's a bit out of our control, I will post back in here as soon as it's live!

**Comment by hazelement** [comment]
No worries, we understand. For the time being, I'm just adding the source code to my project to get it going. Hope it comes out soon.

**Comment by austinkettner** [comment]
Hey guys, this seems to have been published and is available. Take a look!

**Comment by BuddahLD** [comment]
Hey,
Yep, it's successfully compiled into the project (:
Thank you!

**Comment by hazelement** [comment]
same here. Thanks guys!
