### ISSUE TITLE
Preview distorted in landscape orientation

### ISSUE THREAD

**Issue by ghost** [wonderkiln/CameraKit-Android#19]

**Comment by paxxux** [comment]
Hi,

I expierence the same! My activity is in landscape and the camera preview shows a weird angle. But the pictures are taken correctly.

Are you going to fix this soon? I really want to use this library, but I need a solution for this in the next days :(.

Please, please, please!

**Comment by dwillmc** [comment]
I'll try to put a fix in for this tomorrow

**Comment by paxxux** [comment]
awesome! many thanks!

**Comment by dwillmc** [comment]
Looking into this now

**Comment by pmb516** [comment]
Just updated to 0.9.15 and the preview is no longer distorted! Great work.

However, it's now 90 degrees out of rotation in landscape mode 😞

**Comment by kevcgrant** [comment]
In landscape mode the preview is rotated 90 degrees for me as well.

**Comment by pmb516** [comment]
@dwillmc Any update on this?

**Comment by andreidiaconu** [comment]
I don't have a lot of devices but #39 is what worked for my device. @pmb516 @kevcgrant , since you also reported rotation issues, would you mind checking out this branch and trying it on your device? Thanks!

**Comment by kevcgrant** [comment]
I will try tonight and post my findings

**Comment by kevcgrant** [comment]
@andreidiaconu I checked out your branch and tested, everything works except if you use Still mode, the **output** is rotated 90 degrees. The preview is correct for both Standard and Still modes, and the output is correct for Standard as well

**Comment by wangchengyan** [comment]
i need use SurfaceView the Preview still distorted  can you help me? thanks

**Comment by wangchengyan** [comment]
when i set activity landscape 

in xml set CameraView
width="match_parent"
height="476px"

Preview still  distorted

**Comment by dwillmc** [comment]
Now fixed, please update to `0.9.18`.

**Comment by wangchengyan** [comment]
thanks very much!!

**Comment by kuoliangkwong** [comment]
Hi im having the same distortion when I use android:configChanges="orientation|screenSize|keyboardHidden" in my Activity using 0.9.18. 

![device-2017-09-18-143535](https://user-images.githubusercontent.com/8188634/30531191-24a0e5e6-9c7f-11e7-941c-342ff71d99e2.png)
![device-2017-09-18-143517](https://user-images.githubusercontent.com/8188634/30531193-2553d660-9c7f-11e7-9bfa-39c8cff36241.png)

**Comment by YeWin** [comment]
This issue is still not OK on 0.12.3 latest. Do you have any clue?

**Comment by austinkettner** [comment]
I need to confirm, as this seems like a dup of another issue, but reOpened for now!
