### ISSUE TITLE
Update Readme and Docs link .

### ISSUE THREAD

**Issue by ritesh94** [wonderkiln/CameraKit-Android#222]
Please update Readme.md and Documentation website so that users use correct gradle dependency.

**Comment by austinkettner** [comment]
Working on this @ritesh94 -- will merge in something tonight.

**Comment by ritesh94** [comment]
Any idea till when 0.12.0 will be released?
Also for how long are you planning to support the library?

**Comment by ritesh94** [comment]
Thanks Austin for reverting back.
It's good to know that long-term support is provided.
I liked the library and happy to integrate into my projects.

Hopefully it remains open source :smile:
