### ISSUE TITLE
Not rotate in landscape mode

### ISSUE THREAD

**Issue by ste9206** [wonderkiln/CameraKit-Android#224]
Hi, I'm trying to take a photo putting the cameraView in landscape mode, the problem is that it takes the final picture like the portrait mode (it does not rotate the photo). Is there a way to fix it?

**Comment by austinkettner** [comment]
Hi @ste9206 can you please try out the latest Snapshot build of `0.11.3-Snapshot` and reOpen if this is still an issue? If so, please provide the information requested in .github/ISSUE_TEMPLATE.md 

Thank you and hope the latest snapshot build works for you!
