### ISSUE TITLE
error: cannot access LifecycleObserver class file for android.arch.lifecycle.LifecycleObserver not found

### ISSUE THREAD

**Issue by marconealberto** [wonderkiln/CameraKit-Android#233]
I simply added a reference to the CameraView class in order to start and resume the cameraView and I get this error.

If I comment that part in the java files, I still get this error:

 Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.wonderkiln.camerakit.CameraView

The CameraView is inside a Fragment.

**Comment by argiad** [comment]
+ same thing
