### ISSUE TITLE
Huge Delay for captured photo callback

### ISSUE THREAD

**Issue by MuhammedRefaat** [wonderkiln/CameraKit-Android#235]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment

- Android 7.0
- Samsung Note5
- CameraKit v0.12.0

### Steps to Reproduce

Capture an Image using `cameraView.captureImage(callback)` method

Steps:

1. initiating an activity with CameraView and capture Button.
2. press the Button to call `cameraView.captureImage(callback)` method

### Expected Behavior

an Image taken and an immediate callback received at the mentioned callback in captureImage method

### Actual Behavior

Image captured successfully, but I have to wait from 3-4 seconds to receive the callback

### Reproducible Demo

no other projects reproduce that issue.

**Comment by MuhammedRefaat** [comment]
I found the issue, when setting camera preferences through resource declaration in xml, they are not applied, but when setting them programmatically it can read them and they are applied.

My issue was in capture method that should be set to `still ` not  `standard`, so all what I did is :

`  cameraView.setMethod(CameraKit.Constants.METHOD_STILL);`

And now it is working perfectly and image capture callback just received directly.

**Comment by softmarshmallow** [comment]
> I found the issue, when setting camera preferences through resource declaration in xml, they are not applied, but when setting them programmatically it can read them and they are applied.
> 
> My issue was in capture method that should be set to `still ` not `standard`, so all what I did is :
> 
> ` cameraView.setMethod(CameraKit.Constants.METHOD_STILL);`
> 
> And now it is working perfectly and image capture callback just received directly.

This won't work any longer

**Comment by subhan9090** [comment]
This won't work any longer.
Please help!!
