### ISSUE TITLE
Text Recognition via Mobile Vision API

### ISSUE THREAD

**Issue by calebdre** [wonderkiln/CameraKit-Android#246]
### Is this a bug report?
![Yes](https://i.imgur.com/DKUR9Tk.png)

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?
![Yes](https://memegenerator.net/img/instances/15354442/why-of-course.jpg)

It would be awesome to expose an api receiving the current text that's on the screen.
[There's barley any documentation for it](https://developers.google.com/vision/text-overview)  but they do provide a [code lab](https://codelabs.developers.google.com/codelabs/mobile-vision-ocr/) for helping people get started, even though they do A LOT of the work for you (at least the code is there to look at.)

I'm checking out the code from the code lab and will be working on this this weekend. If you guys are open to it, I'd love to include it in the library.

I'm thinking about having a method on the CameraView object like `setTextRecognizerListener` that receives an interface with a method that receives a `SparseArray<TextBlock>`

**Comment by austinkettner** [comment]
We think this is a great idea and would love to see work toward this. We have some thoughts on different directions we could take to achieve this but would really dig seeing a PR on this front! Would be a fun collaboration effort.

**Comment by calebdre** [comment]
#249 merged

**Comment by austinkettner** [comment]
Thanks again for your PR and help here @calebdre very very appreciated!

**Comment by hardysim** [comment]
Is this still available (in `1.0.0-beta3.10`)?
