### ISSUE TITLE
Getting inverted image (180 degrees) from face camera in 0.12.0 

### ISSUE THREAD

**Issue by jaksab** [wonderkiln/CameraKit-Android#248]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment
Samsung S8+ 7 Android
Xiaomi Red Mi Note 3 5.1 Android
And other devices

### About

After update library from 0.11.0 to 0.12.0 I getting inverted image (180 degrees) from face camera, before image was rotated immediately.

**Comment by austinkettner** [comment]
Looking into it @jaksab
