### ISSUE TITLE
is there any option or trick to avoid audio and video permissions? I don't need them

### ISSUE THREAD

**Issue by developer--** [wonderkiln/CameraKit-Android#264]

**Comment by austinkettner** [comment]
If you would like to see a feature of explicitly defining 'required' permission invoked, can you please update this ticket to be more clear on expectations and what would be helpful to you? We can then evaluate adding this in!

**Comment by developer--** [comment]
the library is great and if I need to use it for only app that requires only image capturing, inserting this library causes, that app permissions there is an extra Microphone permission which is useless

**Comment by candalo** [comment]
I think that's a good thing. In my case, I use the lib only for image capturing, thereby the audio and video permissions are useless. Is it possible to make these permissions optional? Something like that:

```java
cameraView.setUseOnlyForImageCapturing(true)
```

In this case, will not be necessary audio and video permissions.

**Comment by candalo** [comment]
There is already a method for this, I saw in the documentation :)

```java
cameraView.setPermissions(CameraKit.Constants.PERMISSIONS_PICTURE);
```

**Comment by developer--** [comment]
yes, but when user goes through app settings, there is an audio permission listed
