### ISSUE TITLE
Failed to resolve: com.wonderkiln:camerakit:0.13.0

### ISSUE THREAD

**Issue by developer--** [wonderkiln/CameraKit-Android#274]

**Comment by dwillmc** [comment]
0.13.0 finished deploying to release maven repo about 30 seconds after this issue opened, can you try again?

**Comment by developer--** [comment]
at this moment 
![screenshot from 2017-12-07 16-34-24](https://user-images.githubusercontent.com/7534778/33715592-895977ec-db6c-11e7-956b-672186225df0.png)

**Comment by dwillmc** [comment]
Oh that's right, it won't work properly until bintray approves the 2 new maven packages for jcenter. For now can you add:

```
maven { url 'https://wonderkiln.bintray.com/maven' }
```

to your maven repos. Hopefully it'll get into jcenter today.

**Comment by developer--** [comment]
great <3 it works now, thanks

**Comment by xp-vit** [comment]
This issue should be closed now, since everything is working.
