### ISSUE TITLE
RuntimeException startPreview failed

### ISSUE THREAD

**Issue by smoan22** [wonderkiln/CameraKit-Android#89]
This error occurs randomly and that's more annoying. Whenever i open the activity in which i am setting up camerakit layout i get Fatal Exception: java.lang.RuntimeException startPreview failed. Code is exactly the same as the one given in documentation so dont think i need to put all of that it here. Full stacktrace is:

`Fatal Exception: java.lang.RuntimeException: startPreview failed
       at android.hardware.Camera.startPreview(Camera.java)
       at com.flurgle.camerakit.Camera1.start(Camera1.java:87)
       at com.flurgle.camerakit.CameraView$3.run(CameraView.java:216)
       at java.lang.Thread.run(Thread.java:818)
`

I am facing 4-5 different errors and i am think of switching cause i am not able to find any answers so hopefully i'll be able to get answers here.

**Comment by dwillmc** [comment]
This should be fixed now with the latest release. Can you update your `build.gradle` to reference `com.wonderkiln:camerakit:0.11.1`. If the issue persists can you please re-open.

Thanks!

**Comment by berviantoleo** [comment]
I still face this problem in version 0.13.1, I get this problem in LG Device

**Comment by ArsalRaza** [comment]
I am also facing this issue in version 0.13.1 .

**Comment by emersoncloud** [comment]
@ArsalRaza Which version of Android are you using? Can you post the code you are using to create the `CameraKitView`? Both the XML and java activity. Thanks!

**Comment by FreelancerNI** [comment]
> @ArsalRaza Which version of Android are you using? Can you post the code you are using to create the `CameraKitView`? Both the XML and java activity. Thanks!

I am also facing this issue in version 0.13.1  on recording video

Device name : LG g4 stylus
Android Version : 6.0

@emersoncloud
